###########################################################################
#######             FOR DEMONSTRATION PURPOSES ONLY                 #######
###########################################################################
#                                                                         #
# If you have not yet read the tutorial, do so now:                       #
#  https://ory-am.gitbooks.io/hydra/content/tutorial.html                 #
#                                                                         #
# This set up is only for demonstration purposes. The login               #
# endpoint can only be used if you follow the steps in the tutorial.      #
#                                                                         #
###########################################################################

version: '2'

services:

  hydra-migrate:
    image: oryd/hydra:$HYDRA_VERSION
    links:
      - postgresd:postgresd
    environment:
      - LOG_LEVEL=debug
      - HYDRA_SYSTEM_SECRET=youReallyNeedToChangeThis
    command:
      migrate sql postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
    restart: on-failure

  keto-migrate:
    image: oryd/keto:$KETO_VERSION
    links:
      - postgresd:postgresd
    environment:
      - LOG_LEVEL=debug
    command:
      migrate sql postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
    restart: on-failure

  oathkeeper-migrate:
    image: oryd/oathkeeper:$OATHKEEPER_VERSION
    links:
      - postgresd:postgresd
    environment:
      - LOG_LEVEL=debug
    command:
      migrate sql postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
    restart: on-failure

  hydra:
    image: oryd/hydra:$HYDRA_VERSION
    links:
      - postgresd:postgresd
    ports:
      - "4444:4444"
    depends_on:
      - hydra-migrate
    command:
      serve --dangerous-force-http
    environment:
      - LOG_LEVEL=debug
      - SYSTEM_SECRET=youReallyNeedToChangeThis
      - DATABASE_URL=postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
      - OAUTH2_CONSENT_URL=http://localhost:4488/consent
      - OAUTH2_LOGIN_URL=http://localhost:4488/login
      - OAUTH2_ISSUER_URL=http://localhost:4444
      - OAUTH2_SHARE_ERROR_DEBUG=1
      - ISSUER_URL=http://localhost:4444
    restart: on-failure

  oathkeeper-proxy:
    image: oryd/oathkeeper:$OATHKEEPER_VERSION
    links:
      - postgresd:postgresd
    ports:
      - "4455:4455"
    depends_on:
      - oathkeeper-api
      - hydra
      - keto
    command:
      serve proxy
    environment:
      - LOG_LEVEL=debug
      - PORT=4455
      - ISSUER_URL=http://localhost:4455/
      - OATHKEEPER_API_URL=http://oathkeeper-api:4456
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_JWK_SET_ID=resources:hydra:jwk:oathkeeper
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_CLIENT_ID=subjects:hydra:clients:oathkeeper-client
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_CLIENT_SECRET=dummy-oathkeeper-secret
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_URL=http://hydra:4444
      - CREDENTIALS_ISSUER_ID_TOKEN_LIFESPAN=1h
      - CREDENTIALS_ISSUER_ID_TOKEN_ISSUER=http://oathkeeper-api:4456
      - AUTHORIZER_KETO_WARDEN_KETO_URL=http://keto:4466
      - AUTHENTICATOR_ANONYMOUS_USERNAME=anonymous
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_CLIENT_ID=subjects:hydra:clients:oathkeeper-client
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_CLIENT_SECRET=dummy-oathkeeper-secret
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_TOKEN_URL=http://hydra:4444/oauth2/token
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_INTROSPECT_URL=http://hydra:4444/oauth2/introspect
      - AUTHENTICATOR_OAUTH2_CLIENT_CREDENTIALS_TOKEN_URL="http://hydra:4444/oauth2/token
    restart: on-failure

  oathkeeper-api:
    image: oryd/oathkeeper:$OATHKEEPER_VERSION
    links:
      - postgresd:postgresd
    ports:
      - "4456:4456"
    depends_on:
      - hydra-migrate
    command:
      serve api
    environment:
      - LOG_LEVEL=debug
      - PORT=4456
      - DATABASE_URL=postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
      - ISSUER_URL=http://localhost:4455/
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_JWK_SET_ID=resources:hydra:jwk:oathkeeper
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_CLIENT_ID=subjects:hydra:clients:oathkeeper-client
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_CLIENT_SECRET=dummy-oathkeeper-secret
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_URL=http://hydra:4444
    restart: on-failure

  keto:
    image: oryd/keto:$KETO_VERSION
    links:
      - postgresd:postgresd
    ports:
      - "4466:4466"
    depends_on:
      - hydra
      - keto-migrate
    environment:
      - LOG_LEVEL=debug
      - DATABASE_URL=postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_CLIENT_ID=subjects:hydra:clients:keto-client
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_CLIENT_SECRET=dummy-keto-secret
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_TOKEN_URL=http://hydra:4444/oauth2/token
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_URL=http://hydra:4444/oauth2/introspect
      - AUTHENTICATOR_OAUTH2_CLIENT_CREDENTIALS_TOKEN_URL=http://hydra:4444/oauth2/token
    restart: on-failure

  configurator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HYDRA_VERSION=$HYDRA_VERSION
        - KETO_VERSION=$KETO_VERSION
        - OATHKEEPER_VERSION=$OATHKEEPER_VERSION
    depends_on:
      - hydra
      - keto
      - oathkeeper-api
    volumes:
      - ../scripts:/scripts
    environment:
      # All of these URLs MUST NOT end with a trailing slash. This is very important!
      - HYDRA_URL=http://hydra:4444
      - KETO_URL=http://keto:4466
      - RESOURCE_SERVER_URL=http://resource-server:4478
      - OATHKEEPER_API_URL=http://oathkeeper-api:4456
      - OATHKEEPER_PROXY_URL=http://oathkeeper-proxy:4455

      # This sets the prefix for all resource, action, and subject names. Be aware that this prefix is automatically
      # applied to all OAuth2 Clients as well.
      - "HYDRA_SUBJECT_PREFIX=subjects:hydra:"
      - "HYDRA_RESOURCE_PREFIX=resources:hydra:"
      - "HYDRA_ACTION_PREFIX=actions:hydra:"
      - "OATHKEEPER_RESOURCE_PREFIX=resources:oathkeeper:"
      - "OATHKEEPER_ACTION_PREFIX=actions:oathkeeper:"
      - "KETO_RESOURCE_PREFIX=resources:keto:"
      - "KETO_ACTION_PREFIX=actions:keto;"

      - OATHKEEPER_HYDRA_JWK_SET_ID=jwk:oathkeeper
      - OATHKEEPER_HYDRA_CLIENT_ID=clients:oathkeeper-client
      - OATHKEEPER_HYDRA_CLIENT_SECRET=dummy-oathkeeper-secret
      - KETO_HYDRA_CLIENT_ID=clients:keto-client
      - KETO_HYDRA_CLIENT_SECRET=dummy-keto-secret
    restart: on-failure

  identity-provider:
    environment:
      - HYDRA_URL=http://hydra:4444
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    image: oryd/hydra-login-consent-node:$LOGIN_CONSENT_VERSION
    ports:
      - "4488:4488"
    restart: on-failure

  identity-provider:
    environment:
      - HYDRA_URL=http://hydra:4444
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - PORT=4488
    image: oryd/hydra-login-consent-node:$LOGIN_CONSENT_VERSION
    ports:
      - "4488:4488"
    restart: on-failure

  consumer:
    build:
      context: ../apps/consumer
      dockerfile: Dockerfile
    depends_on:
      - hydra
      - keto
      - oathkeeper-proxy
    ports:
      - "4477:4477"
    environment:
      - PORT=4477
      - OAUTH2_AUTH_URL=http://localhost:4444/oauth2/auth
      - OAUTH2_TOKEN_URL=http://hydra:4444/oauth2/token
      - OAUTH2_CLIENT_ID=consumer-app
      - OAUTH2_CLIENT_SECRET=consumer-secret
      - OAUTH2_REDIRECT_URL=http://localhost:4477/auth/callback
      - BACKEND_OATHKEEPER_URL=http://oathkeeper-proxy:4455/oathkeeper
      - BACKEND_WARDEN_SUBJECT_URL=http://resource-server:4478/warden/subject
      - BACKEND_WARDEN_TOKEN_URL=http://resource-server:4478/warden/token
      - BACKEND_INTROSPECT_URL=http://resource-server:4478/introspect
      - nodemon start

  resource-server:
    build:
      context: ../apps/resource-server
      dockerfile: Dockerfile
    depends_on:
      - hydra
      - keto
      - oathkeeper-proxy
    ports:
      - "4478:4478"
    environment:
      - PORT=4478
      - OATHKEEPER_KEY_URL=http://oathkeeper-api:4456/.well-known/jwks.json
      - OAUTH2_CLIENT_ID=resource-server
      - OAUTH2_CLIENT_SECRET=introspection-secret
      - OAUTH2_TOKEN_URL=http://hydra:4444/oauth2/token
      - OAUTH2_INTROSPECT_URL=http://hydra:4444/oauth2/introspect
      - KETO_URL=http://keto:4466
      - nodemon start

  postgresd:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=accesscontroldb
