version: '2'

services:

  hydra-migrate:
    image: oryd/hydra:$HYDRA_VERSION
    networks:
      - intranet
    environment:
      - LOG_LEVEL=debug
      - HYDRA_SYSTEM_SECRET=youReallyNeedToChangeThis
    command:
      migrate sql postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
    restart: on-failure

  keto-migrate:
    image: oryd/keto:$KETO_VERSION
    links:
      - postgresd:postgresd
    environment:
      - LOG_LEVEL=debug
    command:
      migrate sql postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
    restart: on-failure

  services:
    build:
      context: ..
      dockerfile: /hydra-bc/Dockerfile
      args:
        - HYDRA_VERSION=$HYDRA_VERSION
        - KETO_VERSION=$KETO_VERSION
        - OATHKEEPER_VERSION=$OATHKEEPER_VERSION
    networks:
      - intranet
    depends_on:
      - hydra-migrate
      - keto-migrate
    ports:
      - "4444:4444"
      - "4445:4445"
      - "4455:4455"
      - "4456:4456"
      - "4466:4466"
    environment:
      # Debuggin
      - LOG_LEVEL=debug
      - HYDRA_OAUTH2_SHARE_ERROR_DEBUG=1

      # Essential configuration for Hydra
      - HYDRA_SYSTEM_SECRET=youReallyNeedToChangeThis
      - HYDRA_DATABASE_URL=postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable
      - HYDRA_OAUTH2_CONSENT_URL=http://localhost:3000/consent
      - HYDRA_OAUTH2_LOGIN_URL=http://localhost:3000/login
      - HYDRA_OAUTH2_ISSUER_URL=http://localhost:4455

      # Essential configuration for Keto
      ## Note that this is the same database as ORY Hydra. You still need to run `keto migrate hydra`
      - KETO_DATABASE_URL=postgres://dbuser:secret@postgresd:5432/accesscontroldb?sslmode=disable

      # Set up URLs which will be used by configuration scripts and to wire everything together
      - OATHKEEPER_ISSUER_URL=http://localhost:4455/
      - OATHKEEPER_ID_TOKEN_SECRET=arandomsecretarandomsecretarando

      # All of these URLs MUST NOT end with a trailing slash. This is very important!
      - HYDRA_URL=http://localhost:4444
      - HYDRA_ADMIN_URL=http://localhost:4445
      - KETO_URL=http://localhost:4466
      - OATHKEEPER_API_URL=http://localhost:4456
      - OATHKEEPER_PROXY_URL=http://localhost:4455

      # This sets the prefix for all resource, action, and subject names. Be aware that this prefix is automatically
      # applied to all OAuth2 Clients as well.
      - "HYDRA_SUBJECT_PREFIX=sn:hydra:"
      - "HYDRA_RESOURCE_PREFIX=rn:hydra:"
      - HYDRA_ACTION_PREFIX=
      - "OATHKEEPER_RESOURCE_PREFIX=rn:oathkeeper:"
      - OATHKEEPER_ACTION_PREFIX=
      - "KETO_RESOURCE_PREFIX=rn:keto:"
      - KETO_ACTION_PREFIX=

      # OAuth2 clients and their secrets, will be used by the respective services as well as configuration scripts
      - HYDRA_ROOT_CLIENT_SECRET=demo-password
      - OATHKEEPER_HYDRA_JWK_SET_ID=jwk:oathkeeper

      - HYDRA_FORCE_ROOT_CLIENT_ID=clients:root
      - HYDRA_FORCE_ROOT_CLIENT_SECRET=demo-password
      - OATHKEEPER_HYDRA_CLIENT_ID=clients:oathkeeper-client
      - OATHKEEPER_HYDRA_CLIENT_SECRET=dummy-oathkeeper-secret
      - KETO_HYDRA_CLIENT_ID=clients:keto-client
      - KETO_HYDRA_CLIENT_SECRET=dummy-keto-secret
      - CONSENT_APP_HYDRA_CLIENT_ID=clients:consent-client
      - CONSENT_APP_HYDRA_CLIENT_SECRET=dummy-consent-secret

#     Uncomment the following line to use mysql instead.
#      - DATABASE_URL=mysql://root:secret@tcp(mysqld:3306)/mysql?parseTime=true

  identity-provider:
    environment:
      - HYDRA_ADMIN_URL=http://services:4445
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    image: oryd/hydra-login-consent-node:$LOGIN_CONSENT_VERSION
    networks:
      - intranet
    ports:
      - "3000:3000"
    restart: unless-stopped

  postgresd:
    networks:
      - intranet
    image: postgres:9.6
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=accesscontroldb

#  Uncomment the following section to use mysql instead.
#  mysqld:
#    image: mysql:5.7
#    environment:
#      - MYSQL_ROOT_PASSWORD=secret

networks:
  intranet:
    driver: bridge
